### ISSUE TITLE
追加するべき機能と修正事項について

### ISSUE THREAD

**Issue by nkm071** [hellocit/robot_follow_line#4]
必須ではないがあると嬉しい機能と修正事項についてまとめる
### 機能について

- 実機でのパラメータ調整
- コードの可読性を上げる

### 修正事項
- C++に変える

**Comment by nkm071** [comment]
シミュレータで実験ができるようにする
gazeboに画像を貼り付ける機能があるのでそれを使用

**Comment by nkm071** [comment]
自分のPCからrostopic pubをして相手側のPCで確認

**Comment by nkm071** [comment]
yolov5_pytorch_rosにより取得した画像が2~3秒ほど遅れる問題があるため，下記のコードのangular.zに制限をつけることで対応する．

https://github.com/hellocit/box_chaser/blob/e264a705044491ee823ad997ba01c670780c1f78/scripts/sub_bbox_2dlidar.py#L40

**Comment by hellocit** [comment]
https://github.com/hellocit/box_chaser/blob/e264a705044491ee823ad997ba01c670780c1f78/scripts/sub_bbox_2dlidar.py#L40C1-L40C121

**Comment by hellocit** [comment]
https://github.com/hellocit/box_chaser/blob/e264a705044491ee823ad997ba01c670780c1f78/scripts/sub_bbox_2dlidar.py#L40C1-L40C121

**Comment by nkm071** [comment]
queueサイズを小さくする．
https://github.com/hellocit/box_chaser/blob/e264a705044491ee823ad997ba01c670780c1f78/scripts/sub_bbox_2dlidar.py#L162

**Comment by nkm071** [comment]
一秒間に送る送信回数を制限する．多すぎると過去に送られてきた画像に対して処理を行っているため10hzあれば十分．
[参考文献](https://qiita.com/Kohei_Koizumi/items/5c8062ce7f71b9bb6e33)

**Comment by nkm071** [comment]
> yolov5_pytorch_rosにより取得した画像が2~3秒ほど遅れる問題があるため，下記のコードのangular.zに制限をつけることで対応する．
> 
> https://github.com/hellocit/box_chaser/blob/e264a705044491ee823ad997ba01c670780c1f78/scripts/sub_bbox_2dlidar.py#L40

細かい実装については制限のangular.zと今計算で算出された値をif文で評価することとする．

**Comment by nkm071** [comment]
2dlidarによる動作指令値も遅れ，箱にぶつかることがあると確認した．

**Comment by nkm071** [comment]
別のリポジトリでの管理となったためissueを閉じる
